### PR TITLE
Make sure `doxygen` and `graphviz` are available.

### PR DESCRIPTION
**Pull request by WhitePeter**
Necessary for testing the `doc-doxygen` target of dunst.

### CODE REVIEW

**Comment by bebehei** [comment]
@WhitePeter Do you need me here to merge/review it?

**Comment by bebehei** [comment]
Ok, I've seen the old commit [b61cc263958837ffd19ba4fcb99ab3e1806ca577](https://github.com/dunst-project/dunst/commit/b61cc263958837ffd19ba4fcb99ab3e1806ca577). This is a good intention to use doxygen in the CI, too.

But there is also `Dockerfile.misc-doxygen`, which only runs doxygen. Using this in the CI instead of installing it in every image will be slimmer. Would you mind integrating this into the CI?

**Comment by WhitePeter** [comment]
> Ok, I've seen the old commit [b61cc263958837ffd19ba4fcb99ab3e1806ca577](https://github.com/dunst-project/dunst/commit/b61cc263958837ffd19ba4fcb99ab3e1806ca577). This is a good intention to use doxygen in the CI, too.
> 
> But there is also `Dockerfile.misc-doxygen`, which only runs doxygen. Using this in the CI instead of installing it in every image will be slimmer. **Would you mind integrating this into the CI?**

I can try, but I know too little about how to do it, I'm afraid. Would that mean to make another PR for this repo or can that be done by a simple change to `.github/workflows/main.yml` in the dunst repo?

**Comment by WhitePeter** [comment]
OK, I think I have got something working, took a little trial and error, though. Please have a look at this [PR](https://github.com/dunst-project/dunst/pull/936), if you don't mind.

**Comment by fwsmit** [comment]
I'll close this PR since I don't think we'll need it

**Pull request closed without merging**
