### PR TITLE
Add Wayland build support

### PR DESCRIPTION
**Pull request by fwsmit**
I haven't tested it, but this should make sure the CI can build the dunst with wayland support.

### CODE REVIEW

**Comment by tsipinakis** [comment]
@bebehei Created/handled the CI items. I'm not sure if he's still active.

If not, I'll have to change the docker image as I don't have access to the DockerHub org. (And also figure out how to update the images)

**Comment by bebehei** [comment]
@tsipinakis Well yes, I'm rather inactive. But I'm still pingable.

IIRC the images should be built automatically, whenever pushed into git master branch here. Only if you add new images, you have to add the new `Dockerfile.<name> -> tag <name>` mapping.

**Comment by bebehei** [comment]
Changes look good.

@fwSmit Have you made `make ci-build` in this repository?

**Comment by fwsmit** [comment]
> Changes look good.
> 
> @fwSmit Have you made `make ci-build` in this repository?

I have now, didn't want to download a million packages. Apparantly ubuntu doesn't have wayland package, so I fixed that.
Arch linux doesn't build for me because of this bug https://bugs.archlinux.org/task/68057 (not because of my changes), so I didn't test further than arch (fedora isn't tested). Maybe we can just push this and see if the CI still works? We can always fix it later

**Comment by bebehei** [comment]
Hey @fwSmit yes, the arch docker image had some issues. I've fixed them now all. Also, I've added debian buster and ubuntu 20.04 images.

I'm currently building the new images with your packages and testing them locally.

**Comment by bebehei** [comment]
Thanks for the hint on Fedora, I'll try to update Fedora, too. Fedora 31 seems to be unsupported now.

**Comment by bebehei** [comment]
I've tested it and pushed your commit directly on HEAD via cherry-pick. In hindsight not the best decision. Your changes went into master, but this PR isn't displayed as merged. Sorry for that.

**Comment by fwsmit** [comment]
> Thanks for the hint on Fedora, I'll try to update Fedora, too. Fedora 31 seems to be unsupported now.

I only meant that the building stopped when arch didn't work. But I'm glad if it helped you.

> I've tested it and pushed your commit directly on HEAD via cherry-pick. In hindsight not the best decision. Your changes went into master, but this PR isn't displayed as merged. Sorry for that.

No problem. Thanks for your work!

**Pull request closed without merging**
